version: '3'
services:
  app:
    container_name: pokedex_api
    build:
      context: .
      dockerfile: ./build/Dockerfile
    env_file:
      - ./build/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

  db:
    container_name: pokedex_db
    image: postgres
    environment:
      POSTGRES_ROOT_PASSWORD: myapp_root_pass
      POSTGRES_DB: pokedex
      POSTGRES_USER: trainer
      POSTGRES_PASSWORD: secret_password!
    volumes:
      - db:/data/pokedex
    ports:
      - 5432:5432
    restart: always

volumes:
  db: